### ISSUE TITLE
Crash at shift-click to empty slot

### ISSUE THREAD

**Issue by VladimirMangos** [RenEvo/pcb#13]
Minecraft crash at  shift-click to empty slot of PCB.

**Comment by RenEvo** [comment]
Thanks, will take a look!

**Comment by VladimirMangos** [comment]
I forgot write: In Minecraft 1.11.2

**Comment by RenEvo** [comment]
Pretty sure it has to do with the non-null inventory changes in latest forge, I still need to do some internal refactoring for this, but I can fix this bug.

**Comment by renevo** [comment]
@VladimirMangos published 1.11.2-1.5.1 to curse.

**Comment by VladimirMangos** [comment]
Thank you! Work now)
