### ISSUE TITLE
Crashes 1.8 Client

### ISSUE THREAD

**Issue by kreezxil** [RenEvo/pcb#4]
http://paste.ee/p/rig66

On startup.

**Comment by RenEvo** [comment]
I am guessing you figured this one out? From the crashlog, it looks like the Cookie Jar from Mr. Crayfish crashed the game for you.

com.mrcrayfish.furniture.render.tileentity.CookieRenderer

Might want to let them know :)

**Comment by kreezxil** [comment]
actually, craft++ was causing issues. so I actually posted to wrong place.
:(
